import = ["~/.config/alacritty/themes/themes/cattpuccin_mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

# [colors.bright]
# black = "#686868"
# blue = "#59C2FF"
# cyan = "#95E6CB"
# green = "#C2D94C"
# magenta = "#FFEE99"
# red = "#F07178"
# white = "#FFFFFF"
# yellow = "#FFB454"

# [colors.normal]
# black = "#01060E"
# blue = "#53BDFA"
# cyan = "#90E1C6"
# green = "#91B362"
# magenta = "#FAE994"
# red = "#EA6C73"
# white = "#C7C7C7"
# yellow = "#F9AF4F"

# [colors.primary]
# background = "#0A0E14"
# foreground = "#B3B1AD"

[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "alacritty"

[font]
size = 9.0

[font.bold]
family = "NotoSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "NotoSansM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "NotoSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "NotoSansM Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.1
