import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
LANG = "en_IE.UTF-8"
LC_CTYPE = "en_IE.UTF-8"
TERM = "alacritty"

[font]
size = 9.0

[font.bold]
family = "NotoSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "NotoSansM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "NotoSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "NotoSansM Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.9
dynamic_padding = true
blur = true
