[colors]
draw_bold_text_with_bright_colors = true

[env]
LANG = "en_IE.UTF-8"
LC_CTYPE = "en_IE.UTF-8"
TERM = "alacritty"

[font]
size = 10.0

[font.normal]
# family = "IosevkaTerm NFM"
# family = "ZedMono Nerd Font"
# family = "M+1Code Nerd Font"
# family = "Hack Nerd Font"
# family = "ShureTechMono Nerd Font"
family = "Maple Mono NF CN"
style = "Regular"

[font.bold]
# family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.bold_italic]
# family = "Iosevka Nerd Font Mono"
style = "Bold Italic"

[font.italic]
# family = "Iosevka Nerd Font Mono"
style = "Italic"

[window]
decorations = "None"
# padding = { x = 3, y = 3 }
opacity = 1.0
dynamic_padding = false
blur = false

[general]
import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[cursor]
style = { blinking = "On" }
