theme = "base16_transparent"

[editor]
line-number = "absolute"
mouse = true
scrolloff = 3
middle-click-paste = true
scroll-lines = 3
shell = ["bash", "-c"]
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-completion = true
auto-format = true
idle-timeout = 400
completion-trigger-len = 1
completion-replace = true
auto-info = true
true-color = true
rulers = [80, 88, 120]
auto-pairs = true
cursorline = true
bufferline = "always"
color-modes = true
popup-border = "all"
end-of-line-diagnostics = "hint"

# [editor.gutters.line-numbers]
# min-width = 3

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "file-type",
  "file-encoding",
  "file-line-ending",
  "file-modification-indicator",
  "version-control",
]
center = []
right = [
  "diagnostics",
  "workspace-diagnostics",
  "selections",
  "primary-selection-length",
  "position",
  "total-line-numbers",
]
separator = "|"


[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true
max-depth = 7

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "all"
nbsp = "all"
nnbsp = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "▏"

[editor.soft-wrap]
enable = true

[keys.normal]
# Git UIs
A-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
A-S-g = [":new", ":insert-output gitui", ":buffer-close!", ":redraw"]

# Call the AI prompt using smartcat
# C-a = [
#   ":n",                                                        # Open buffer
#   ":w! %sh{echo /tmp/helix/ai-$(date --iso-8601=seconds).md}", # Write immediately in MD for LSP to pick up context
#   # ":insert-output echo '!CC\n<|user|>'",                     # Create a base for LSP action to be triggered
#   ":insert-output echo '> '", # Enter the MD-like prompt for smartcat
#   # ":goto 3",                                                 # Go to end of file (in case of !CC)
#   "goto_line_end",
#   "insert_at_line_end",
#   ":redraw",
# ]
# C-x = [
#   """:| sc -r -c %sh{echo $(fd -tf -c never --one-file-system \
#   -S=-1M \
#   -E='**/*lock*' -E='**/*.txt' \
#   -E='**/*.png' -E='**/*.svg' -E='**/*.jpeg' -E='**/*.jpg' \
#   -E='**/Cargo.lock' -E='**/.cargo' -E='**/*.scm' \
#   -E='**/node_modules' -E='**/package-lock.json' -E='**/yarn.lock' -E='**/pnpm-lock.*' \
#   -E='**/.venv' -E='**/.env' \
#   -E='**/target' \
#   -E='**/dist' \
#   -x file -i | rg ' text/plain;' | cut -d: -f1 | tr '\n' ' ')}""",
#   ":redraw",
# ]
# C-v = [":| sc -re -c %sh{echo $(fd -tf -c never . | tr '\n' ' ')}", ":redraw"]

# Call the AI prompt using llama.cpp and curl
C-a = [
  ":n",                                                        # Open buffer
  ":w! %sh{echo /tmp/helix/ai-$(date --iso-8601=seconds).md}", # Write immediately in MD for LSP to pick up context
  # ":insert-output echo '!CC\n<|user|>'",                     # Create a base for LSP action to be triggered
  ":insert-output echo '> '", # Enter the MD-like prompt for smartcat
  # ":goto 3",                                                 # Go to end of file (in case of !CC)
  "goto_line_end",
  "insert_at_line_end",
  ":redraw",
]
C-x = [
  ''':| jq -Rc "{
  stream: false,
  prompt: .,
  messages: [
  {
    role: \"system\",
    message: \"You are skilled programmer with a keen eye for detail and an emphasis on readable code.
    You have been tasked with acting as a smart version of the cat unix program.
    You take text and a prompt in and write text out.
    For that reason, it is of crucial importance to just write the desired output.

    Follow these rules if user has provided context (e.g. the format of the file is Markdown file):
    - Output the thinking and every steps you take as usual.
    - Make sure to do a proper formatting for provided context,
    for example, follow Markdown formatting, if it's requested.
    - Keep the explanation short and try not to repeat the chain of thought multiple times.

    Follow these rules if no context was provided:
    - Do not under any circumstance write any comment
    or thought as your output will be piped into other programs.
    - Do not write the markdown delimiters for code as well.
    - Do not surround the output with \`\`\` markers, as they are not required.
    - Sometimes you will be asked to implement or extend some input code.
      Same thing goes here, write only what was asked because what you write
      will be directly added to the user's editor.
    - Make sure to keep the indentation and formatting.
  \"
  },
  {
    role: \"user\",
    message: .
  }
  ]}" |
  curl -X POST -sN --max-time 30 --json @- http://localhost:3001/v1/completions |
  jq -r ".choices?.[0].text?"
  ''',
  ":redraw",
]
