# Language servers config
[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }
nu-lsp = { command = "nu", args = ["--lsp"] }

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }
file-types = ["yaml", "yml"]

# Python setup
[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = " " }
roots = ["pyproject.toml", "pyrightconfig.json", "Poetry.lock"]
language-servers = ["pyright", "ruff"]
formatter = { command = "black", args = [
  "--line-length",
  "88",
  "--quiet",
  "-",
] }

# WEB languages
[[language]]
name = "html"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "css"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "css"] }

# JS/TS family config
[[language]]
name = "javascript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "tsx"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "jsx"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "json"
auto-format = true
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "nu"
auto-format = true
language-servers = ["nu-lsp"]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-w", "-s", "-i", "2", "-sr", "-bn"] }
