#!/usr/bin/bash

# variables
config="$HOME/.config/hypr"
scripts="$config/scripts"

# waybar
"$scripts/launch_waybar" &

# gsettings
"$scripts/import-gsettings"

# wallpaper set to cloud.png
# swww init && swww img "$HOME/.config/hypr/wallpapers/houses.jpg" --transition-type center --transition-fps 144

# effects
#"$scripts/rgb" &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
fcitx5 -d &
corectrl --minimize-systray &
